### ISSUE TITLE
数据库架构设计

### ISSUE THREAD

**Issue by wanglizhao-ai** [xiaoliangliang123/minicloud#1]
希望能增加个数据库高可用架构设计理论及实现

**Comment by xiaoliangliang123** [comment]
谢谢你的issues ，目前已经支持分库分表，写在了对应的项目yml里，是基于shardingshpere的，直接在项目的yml或者对应的nacos yml内修改成自己的分库分表策略即可，目前1主2从都是连在了一个本地库内：
比如：

> datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:mini-cloud-master}:${MYSQL_PORT:3306}/${MYSQL_DB:mini_cloud_upms}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: root
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:mini-cloud-slave1}:${MYSQL_PORT:3306}/${MYSQL_DB:mini_cloud_upms}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: root
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:mini-cloud-slave2}:${MYSQL_PORT:3306}/${MYSQL_DB:mini_cloud_upms}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: root
    sharding:
      master-slave-rules:
        master:
          master-data-source-name: master
          slave-data-source-names: slave0,slave1

欢迎积极提出问题~
